name: GraalVM Native Image Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io   # Uncomment if you're pushing to GitHub
  IMAGE_NAME: ${{ github.repository }}  # Uncomment if you're pushing to GitHub


jobs:
  build:
    name: Simple Spring Boot Sample on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest-x64 , macos-latest-arm64 ]
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          gds-token: ${{ secrets.GDS_TOKEN }}
          java-version: '21'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build Native Image Using Maven
        run: mvn -Pnative native:compile

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          path: target/api


      - name: Upload native binary to GitHub Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          files: target/api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
